In [1]:
import numpy as np

In [3]:
array = [3, 5, 9, 16, 25]
float_array = [float(num) for num in array]
print(float_array)


[3.0, 5.0, 9.0, 16.0, 25.0]


In [7]:
array = [1.2, -3.6, 8.99999, 16.1]
int_array = [int(num) for num in array]
print(int_array)


[1, -3, 8, 16]


In [17]:

matriz = np.zeros((3, 9))
print(matriz)


[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [19]:
matriz = np.ones((6, 7), dtype=int)
print(matriz)


[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [21]:
matriz_identidade = np.eye(4)
print(matriz_identidade)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
array_aleatorio = np.random.rand(5)
print(array_aleatorio)


[0.99210357 0.22965647 0.17637646 0.24132989 0.78427352]


In [34]:
matriz_aleatoria = np.random.randint(0, 6, (3, 6))
print(matriz_aleatoria)

matriz_exercicios = np.array([[4, 6, 8], [-4, 3, 2], [22, -15, 12]])
print(matriz_exercicios)


[[1 4 0 4 4 1]
 [2 3 0 4 5 5]
 [5 1 1 5 2 0]]
[[  4   6   8]
 [ -4   3   2]
 [ 22 -15  12]]


In [36]:
valor_maximo = np.max(matriz_exercicios)
print(valor_maximo)


22


In [38]:
valor_minimo = np.min(matriz_exercicios)
print(valor_minimo)


-15


In [40]:
soma_elementos = np.sum(matriz_exercicios)
print(soma_elementos)


38


In [42]:
media_elementos = np.mean(matriz_exercicios)
print(media_elementos)


4.222222222222222


In [44]:
array = [13, -2, 6, 8, 23, 15, 3, 90, 4, 10, 56, 12]
quarto_elemento = array[3]
print(quarto_elemento)


8


In [47]:
ultimos_tres_elementos = array[-3:]
print(ultimos_tres_elementos)


[10, 56, 12]


In [49]:
elementos_a_partir_posicao_2 = array[2:]
print(elementos_a_partir_posicao_2)


[6, 8, 23, 15, 3, 90, 4, 10, 56, 12]


In [51]:
array_segmento = array[1:6]
print(array_segmento)


[-2, 6, 8, 23, 15]


In [53]:
sub_array = array[4:8]
print(sub_array)


[23, 15, 3, 90]


In [55]:
matriz = [[1, 3, 16, -25, 14],
          [2, 0, 10, 5, 17],
          [19, 4, 8, 15, 13],
          [7, 12, -5, 14, 0]]

terceira_linha = matriz[2]
print(terceira_linha)


[19, 4, 8, 15, 13]


In [57]:
quarta_coluna = [linha[3] for linha in matriz]
print(quarta_coluna)


[-25, 5, 15, 14]


In [59]:
elemento_valor_10 = matriz[1][2]
print(elemento_valor_10)


10


In [61]:
nova_matriz = [[0, 10, 5],
               [4, 8, 15]]
print(nova_matriz)


[[0, 10, 5], [4, 8, 15]]


In [63]:
matriz = np.array([[2, -1, 15, 24],
                   [-3, 18, 4, 25],
                   [9, 10, -13, 7]])

nova_matriz = np.where(matriz % 2 == 0, 2, 1)
print(nova_matriz)


[[2 1 1 2]
 [1 2 2 1]
 [1 2 1 1]]
